name: Gutenberg RSS Updates

on:
  # Daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-datasets:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ env.GITHUB_PAT }}

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet libxml2-utils  # Install xmllint

      - name: Process RSS
        run: bash .github/scripts/process_rss.sh

      - name: 🚀 Commit if rss-updates.csv has changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data-raw/rss-updates.csv
          if git diff --cached --quiet; then
            echo "No changes in rss-updates.csv; skipping commit."
          else
            git commit -m "🤖 Auto-update Project Gutenberg RSS CSV"
            git push
          fi
