name: Gutenberg RSS Updates

on:
  # Daily at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-rss:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ env.GITHUB_PAT }}
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Process RSS
        run: Rscript process_rss.R
      - name: 🚀 Commit if rss-updates.csv has changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data-raw/rss-updates.csv
          if git diff --cached --quiet; then
            echo "No changes in rss-updates.csv; skipping commit."
          else
            git commit -m "🤖 Auto-update Gutenberg CSV"
            git push
          fi
